### ISSUE TITLE
Submission form language improvements. 

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#16]
- [x] `ppl`  => `attendees`

- [x] “If you are a non Israeli speaker…” - Perhaps “Non-Hebrew speakers are most welcome, but bear in mind that most of the contents is going to be in Hebrew”.

- [x] "What do you get for X?” - I bit confusion in my opinion. Perhaps “Submission perks” or “Submitters’ perks”

- [x] Add 2016 to this list: 
  > You may get a good sense of the topics we're interested in by looking into previous events: Reversim Summit 2013 and Reversim Summit 2014 and Reversim Summit 2015.

- [x] I would add to this “We are looking for deep, hard-core technical sessions which exemplify outstanding and unique work or learnings where you personally have a personal edge” as a new paragraph right after this one: 
  > Generally speaking - we are not looking for “intro to something software” or “something software 101”. We’re looking for something of greater depth. However, we are open to session “intro to something that isn’t software”, as long is this something is of general interest, for example “intro to moonwalking and breakdance”

- [x] Rename “Talk proposal” to “Session proposal”. And if there are other 

- [x] The outline description is a little vague. “Describe the topics you will cover and an outline of the story you are telling. Include timing and slide details.”. Let me suggest this: 
   > Describe the outline of your session. An outline is a single bullet per planned slide with a short sentence of what the slide is about. (it’s OK to later change it, but please lay out your current plan). This is crucial information for being able to accept your session so please provide quality outline. Sessions with low quality outline will unfortunately not be considered.

**Comment by amitzur** [comment]
How about "which derive from your personal experience" instead of:
> where you personally have a personal edge

**Comment by amitzur** [comment]
the outline description is a bit harsh IMO. "will not be considered" - tough wording

**Comment by rantav** [comment]
Alright @amitzur feel free to reword... I just want to make sure we're clear that outline is not a nice-to-have, it's required.
