### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#18]
Please add the following tracking code when you get a chance `UA-36904731-4`.
It's for RS17. I'll send you an invite soon

@amitzur

**Comment by amitzur** [comment]
something very strange is happening. I put the code yesterday, but I'm not seeing the right code in the network. Instead it's UA-141520-1. But in the code it's fine.
In addition there is a number of users that's not zero in the dashboard, so obviously some clients send the correct code. But I can't figure out who and why

**Comment by rantav** [comment]
Indeed there are two GA accounts on the page http://jmp.sh/kbomMZz and I don't know if they are "stealing" events from each other (I guess they can co-exist)

I think this could be eventbrite http://pub-db.com/google-analytics/UA-141520.html
Try to disable the eventbrite widget, see if it helps.

**Comment by amitzur** [comment]
great catch!

**Comment by rantav** [comment]
I think we're fine here, analytic's working, closing
