### ISSUE TITLE
Sponsors on the site

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#20]
During the upcoming voting phase there's going to be a lot of traffic to the website. 
Therefore we want our sponsors to be on the site with all their details. 

Just opening this issue as a reminder.... @amitzur and @shlomihassan please work together to get this online..

**Comment by shlomihassan** [comment]
@rantav i know sent reminder to the sponsors to send me the logo and description 
also @amitzur and i talked about it already
