### ISSUE TITLE
Website agenda readiness

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#22]
For the next version of the website (published agenda) we need: 

- [x] update all accepted/rejected sessions from the spreadsheet master tab
- [x] `/agenda` page
- [x] Add a top-level menu item for `/agenda`
- [x] Main call to action on the home page pointing to the agenda page
- [x] `/speakers` page listing all speakers (and session mini-profile)
- [ ] `/sessions` page listing all sessions (and speaker mini-profile)
- [ ] Hide `/proposals` from navigation (but do not disable it, **I still want to be able to access all submitted sessions** on that URL)
- [x] Add Keynotes as sessions (details with Ran and Shlomi)
- [ ] "You might also be interested at" to link only to accepted sessions http://jmp.sh/WkmZpnZ

After this - in about two more days add: 
- [ ] `/register` with a link to registration site and explanation about payment (if relevant, still TBD)
- [ ] Main call to action on the landing page poiting to /register

**Comment by amitzur** [comment]
what's the due date again?

**Comment by rantav** [comment]
in about a week. 
We expect to have an agenda ready early next week so by the end of next week I hope to have the site ready

**Comment by rantav** [comment]
@amitzur updated the checklist with 

>  Add Keynotes as sessions (details with Ran and Shlomi)

We have the speaker details and abstracts for the two keynotes.

**Comment by rantav** [comment]
@amitzur added another bullet to the list 

> "You might also be interested at" to link only to accepted sessions

**Comment by rantav** [comment]
how's it going now? @amitzur @guywarburg 

Note that I added a small item to the list
> Add a top-level menu item for `/agenda`

**Comment by amitzur** [comment]
for second phase:
- [ ] edit speaker details
- [ ] You might also be interested at (not implemented yet for new website)
- [ ] hidden `/proposals` page

**Comment by amitzur** [comment]
New issues created which cover this functionality
