### ISSUE TITLE
Add keynote: Digital Culture/Clutter

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#23]
This is the keynote for day 1.

# Digital Culture/Clutter
### Pains and Gains of the Net

Everything is increasingly immersed in the digital. Atoms are being replaced by bits. The interpersonal is morphing into something else, more virtual and less organic. This talk is about the cultural, psychological, economic and sociological implications of these developments. Rather than falling into either utopian or dystopian traps, we will attempt a dispassionate  analysis of what is happening. What gets lost in the exchange for the gains of the digital? What do we gain in return?
 
We will ask the questions surrounding the Death(?) of Privacy, Distance, Center, Time, Tangibility, Books, Classroom, Truth, Conversation, Promise, Choice, Memory and perhaps even the Death of Death itself.
 
Science Fiction, Film, Art, Engineering and the Halls of Science are engaging with these questions. They can be morbid (Death?) or promising (Birth?). In this talk we will lay down the parameters and perimeters of the issues involved.

# Speaker: Sheizaf Rafaeli 
Speaker bio and photo: Take from his website http://gsb.haifa.ac.il/~sheizaf/Bio.htm

**Comment by amitzur** [comment]
How should this be added? Should I just add it manually?
Should this be added for the published agenda milestone?

**Comment by rantav** [comment]
Add it manually somehow. He doesn't need to be involved. Maybe fake a user or something, I don't know.. 

The session needs to be listed like with all other sessions in `/sessions` and the speaker in `/speakers` and of course in the agenda. 

that's the "what", you do the "how"...
