### ISSUE TITLE
Speakers should be able to edit their bio, photo, title, abstract. (urgent) 

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#24]
The accepted speakers (or anyone for that matter) should now be able to edit their personal details or session details. 
We send them the accept emails today and tomorrow and ask them to update their personal or sessions details if they need to. 

So that means it's urgent...

**Comment by amitzur** [comment]
anyone should be able to edit? not only the accepted ones?

**Comment by amitzur** [comment]
Ok, opening up for everyone for now.

**Comment by amitzur** [comment]
done

**Comment by rantav** [comment]
yeah, anyone, that's easier...

**Comment by rantav** [comment]
Emails are starting to be sent today, so just making sure you know that...

**Comment by rantav** [comment]
Isn't this done @amitzur ?

**Comment by amitzur** [comment]
see issue #45
