### ISSUE TITLE
New Website - Backwards compatibility

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#31]
The new website design looks great. It's clean and intuitive. 
I want to make sure that next year we have a clean start, therefore I suggest to implement all the historical features in the new site as well and hide them under feature flags. 
To name a few: 

1. Call for papers
2. Votes
3. /proposals and all the session specific pages. 
4. Allow team members to register and add bio using a secret invite code. 

What else?...

**Comment by amitzur** [comment]
More or less that's it. There are more subtleties like the voting FAQ, but I will compile a more comprehensive list of tasks

**Comment by amitzur** [comment]
I've created issues for these items individually
