### ISSUE TITLE
Reduce cloudinary image size to reduce $$ burn

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#32]
Looks like we're still using the full image sizes, which caused us to reach the 100% of bandwidth again. 
This can easily be fixed by appending URL parameters that reduce image size, that's what cloudinary is good at. 

http://jmp.sh/ZcZtb28
http://jmp.sh/au1NDWN

**Comment by rantav** [comment]
@amitzur for now I have just upgraded to the bigger plan for $100, but it's just a waste of $$, so please try to fix it...

**Comment by amitzur** [comment]
I already wrote the code to do it, but had a bug in it.
So now it's fixed - homepage cloudinary hit size down 10x from 27MB to 2.4MB
