### ISSUE TITLE
Getting There section 

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#34]
I suggest to replace the `Location` link with a `Getting There` link and include the following content: 

1. Address of the college, like today. A map (like today) could be nice but not a must
2. Parking: There is a large parking lot just outside the college to the service of our guests. A daily voucher costs 10ILS for the day and can be purchased onsite
3. You may use the train and get off at Moshe Dayan station, where our shuttle will take you to the college. The shuttle will run 8am-10am and then again at the end of the event. 
4. Add the college map ![college-of-management](https://user-images.githubusercontent.com/87037/31250756-8a201a56-aa24-11e7-973f-e0afa38b5287.png)

**Comment by amitzur** [comment]
done
