### ISSUE TITLE
Add link to ical on the schedule page

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#35]
Please add a link to the following ical link with an explanation that this can be added to most calendar software, including google calendar and it would make viewing the agenda easier on mobile devices during the conference. 

https://calendar.google.com/calendar/ical/feqb8evhmssuc5v0lusrtjkhp4%40group.calendar.google.com/public/basic.ics

You may use the following image as a link: ![ical](https://user-images.githubusercontent.com/87037/31293859-696be80e-aae1-11e7-89a1-f85fab0c10f3.gif)

**Comment by amitzur** [comment]
added to the schedule page
